(in-package :lambda)

(cffi:defcstruct input-event
  (event-type :uint8)
  (modifiers  :uint8)
  (code       :uint16)
  (x          :float)
  (y          :float))

(cffi:defcfun ("lambda_input_buf_ptr"       %input-buf-ptr)       :pointer)
(cffi:defcfun ("lambda_input_write_index"   %input-write-index)   :uint32)
(cffi:defcfun ("lambda_input_set_read_index" %input-set-read-index) :void (n :uint32))

;; Event types
(defconstant +key-down+ 1)
(defconstant +key-up+   2)

;; Modifier bits
(defconstant +mod-shift+ 1)
(defconstant +mod-ctrl+  2)
(defconstant +mod-alt+   4)
(defconstant +mod-super+ 8)

;;; Key codes
(defconstant +key-a+  1)
(defconstant +key-b+  2)
(defconstant +key-c+  3)
(defconstant +key-d+  4)
(defconstant +key-e+  5)
(defconstant +key-f+  6)
(defconstant +key-g+  7)
(defconstant +key-h+  8)
(defconstant +key-i+  9)
(defconstant +key-j+ 10)
(defconstant +key-k+ 11)
(defconstant +key-l+ 12)
(defconstant +key-m+ 13)
(defconstant +key-n+ 14)
(defconstant +key-o+ 15)
(defconstant +key-p+ 16)
(defconstant +key-q+ 17)
(defconstant +key-r+ 18)
(defconstant +key-s+ 19)
(defconstant +key-t+ 20)
(defconstant +key-u+ 21)
(defconstant +key-v+ 22)
(defconstant +key-w+ 23)
(defconstant +key-x+ 24)
(defconstant +key-y+ 25)
(defconstant +key-z+ 26)

(defconstant +digit-0+ 30)
(defconstant +digit-1+ 31)
(defconstant +digit-2+ 32)
(defconstant +digit-3+ 33)
(defconstant +digit-4+ 34)
(defconstant +digit-5+ 35)
(defconstant +digit-6+ 36)
(defconstant +digit-7+ 37)
(defconstant +digit-8+ 38)
(defconstant +digit-9+ 39)

(defconstant +space+     40)
(defconstant +enter+     41)
(defconstant +escape+    42)
(defconstant +backspace+ 43)
(defconstant +tab+       44)
(defconstant +delete+    45)
(defconstant +insert+    46)
(defconstant +home+      47)
(defconstant +end+       48)
(defconstant +page-up+   49)
(defconstant +page-down+ 50)

(defconstant +comma+         55)
(defconstant +period+        56)
(defconstant +slash+         57)
(defconstant +semicolon+     58)
(defconstant +quote+         59)
(defconstant +bracket-left+  60)
(defconstant +bracket-right+ 61)
(defconstant +backslash+     62)
(defconstant +minus+         63)
(defconstant +equal+         64)
(defconstant +backquote+     65)

(defconstant +arrow-up+    80)
(defconstant +arrow-down+  81)
(defconstant +arrow-left+  82)
(defconstant +arrow-right+ 83)

(defconstant +shift-left+    90)
(defconstant +shift-right+   91)
(defconstant +control-left+  92)
(defconstant +control-right+ 93)
(defconstant +alt-left+      94)
(defconstant +alt-right+     95)
(defconstant +super-left+    96)
(defconstant +super-right+   97)

(defconstant +f1+  100)
(defconstant +f2+  101)
(defconstant +f3+  102)
(defconstant +f4+  103)
(defconstant +f5+  104)
(defconstant +f6+  105)
(defconstant +f7+  106)
(defconstant +f8+  107)
(defconstant +f9+  108)
(defconstant +f10+ 109)
(defconstant +f11+ 110)
(defconstant +f12+ 111)

(defconstant +caps-lock+    120)
(defconstant +num-lock+     121)
(defconstant +scroll-lock+  122)
(defconstant +print-screen+ 123)
(defconstant +pause+        124)

;;; Polling
(defparameter *input-buf* (%input-buf-ptr))
(defvar *read-index* 0)

(defun poll-events ()
  "Read all pending input events from the ring buffer.
Returns a list of (event-type code modifiers) lists."
  (let ((write (%input-write-index))
        (read *read-index*)
        (event-size (cffi:foreign-type-size '(:struct input-event)))
        (events nil))
    (loop while (/= read write) do
      (let ((ptr (cffi:inc-pointer *input-buf* (* (mod read 256) event-size))))
        (cffi:with-foreign-slots ((event-type modifiers code) ptr (:struct input-event))
          (push (list event-type code modifiers) events)))
      (setf read (ldb (byte 32 0) (1+ read))))
    (setf *read-index* read)
    (%input-set-read-index read)
    (nreverse events)))

;; Callback
(cffi:defcfun ("lambda_set_input_callback" %set-input-callback) :void
  (cb :pointer))

(cffi:defcallback input-tick :void ()
  (dolist (ev (poll-events))
	(format t "~S~%" ev)))

(%set-input-callback (cffi:callback input-tick))
